FROM apache/airflow:2.7.0

# Build additional dockers
#   TODO: Is build should be only for worker?
# RUN cd /dockerfiles/sklearn && docker build . -t sklearn_image
RUN pip install --no-cache-dir mlflow